Checkpoint #8.7: Updates and code-maintenance
  Vim/Neovim:
  * Patch 'mason-conform.nvim'.
  * Update obsolete settings for 'conform.nvim'.

  + Add missing `\hR` in 'gitsigns.nvim'.
  + Improve settings for 'dial.nvim'.
  + Add mappings to toggle GitHub Copilot in Neovim.
  + Add some plugins like 'neogit' and 'lazydev' (for lua).
  + Save pymove (but will be designed as a separate plugin) just in case.
  + Lower severity of cspell diagnostic to exclude it from set of diagnostics
    to navigate through.
  + Copy easily to a named register (<Space>yy, <Space>y<Space>, <Space>yp,
    and other mappings).

  c Return 'lukoshkin/tidy.nvim' since not it is safe.
  c Some changes that does not really change things.

  Shell:
  + Improve `difff` command: allow to choose between regex and shell globbing
    filtering. Should be also moved to a separate shell plugin.
  * Fix `bak` command when applying on files not on `$PWD` and dotted ones.

---
This is a commit fraction #7.
It intends to finish this branch of development.

NOTE: Checkpoint #9 is not finished.
NOTE: Checkpoint #10 is not finished.

We got back to 8-th checkpoint :)
But we will get back to the rest soon.

Next commits (or the last fraction) may be about:
- optimizing loading of plugins with `lazy = true` option.
- updating README

diff --git a/difff-1.2.1-2/usr/local/bin/difff b/difff-1.2.1-2/usr/local/bin/difff
--- a/difff-1.2.1-2/usr/local/bin/difff
+++ b/difff-1.2.1-2/usr/local/bin/difff
@@ -1,13 +1,17 @@
 #!/bin/bash
 
 if [[ $EDITOR = nvim ]]; then
-  vimdiff () { nvim -d "$@"; }
+  vimdiff() { nvim -d "$@"; }
 fi
 
-## On which exit status to print help message
-PRINT_ES=21
+NC='\033[0m'
+BRED='\033[1;31m'
+GREEN='\033[0;32m'
+BGREEN='\033[1;32m'
+PRINT_ES=21 # On which exit status to print help message
+REGEX_PATTERN=false
 
-help_msg () {
+help_msg() {
   printf 'Usage from anywhere:\n'
   printf '    diff [<options>] -D1 <project> -D2 <counter>\n'
   printf 'From a <project> directory:\n'
@@ -18,6 +22,7 @@ help_msg () {
   printf '%-40s %s\n' '-s|--staged' 'Use --staged flag in `git diff`.'
   printf '%-40s %s\n' '-n|--dry-run' 'Show how it would be w/o doing anything.'
   printf '%-40s %s\n' '-a|--add-new' 'Add new files from the counterpart directory.'
+  printf '%-40s %s\n' '--regex' 'Use regex instead of shell pattern matching.'
 
   printf '%-40s %s\n' '-m|--mode=<mode>' '<mode> can be git or folder.'
   printf '%-40s %s\n' '-d|--folder=<dir>' 'Parent folder of the target directory limiting #files to be compared.'
@@ -26,26 +31,36 @@ help_msg () {
   printf '%-40s %s\n' ' ' 'Leave trailing "/" to treat as a directory.'
 }
 
-
-function matches_path () {
+function matches_path() {
   local target=$1
   shift
 
-  for path in "$@"; do
-    [[ -n "$path" ]] && [[ "$target" =~ $path ]] && return 0
-  done
+  if $REGEX_PATTERN; then
+    for path in "$@"; do
+      [[ -n "$path" ]] && [[ "$target" =~ $path ]] && return 0
+    done
+  else
+    for path in "$@"; do
+      case $target in
+      $path) return 0 ;; # Do not use quotes around $path
+      *) ;;
+      esac
+    done
+  fi
 
   return 1
 }
 
-
-function difff () {
-  local long_opts='ignore:,trim-cnt:,folder:,mode:,staged,dry-run,add-new,D1:,D2:,help'
-  local short_opts='i:t:,d:,m:,s,n,a,h'
+function difff() {
+  local long_opts='D1:,D2:,ignore:,trim-cnt:,folder:,mode:,staged,dry-run,add-new,regex,help'
+  local short_opts='i:t:,d:,m:,s,n,a,r,h'
   local params
 
-  params=$(getopt -o $short_opts -l $long_opts --name "$0" -- "$@") \
-    || { echo Aborting..; return $PRINT_ES; }
+  params=$(getopt -o $short_opts -l $long_opts --name "$0" -- "$@") ||
+    {
+      echo Aborting..
+      return $PRINT_ES
+    }
   eval set -- "$params"
 
   local folder prefix
@@ -58,6 +73,7 @@ function difff () {
       -a|--add-new)     add_new=yes; shift ;;
       -m|--mode)        mode=$2; shift 2;;
       -i|--ignore)      ignore+=( "$2" ); shift 2 ;;
+      -r|--regex)       REGEX_PATTERN=true; shift 1 ;;
       --D2)             prefix=$2; shift 2 ;;
       -d|--D1|--folder) folder=$2; shift 2 ;;
       -t|--trim-cnt)    trim_cnt=$2; shift 2 ;;
@@ -70,7 +86,7 @@ function difff () {
   if [[ -z $prefix ]]; then
     if [[ -z $1 ]]; then
       echo Prefix not set
-      return $PRINT_ES;
+      return $PRINT_ES
     else
       prefix=$1
       shift
@@ -79,11 +95,17 @@ function difff () {
 
   if [[ -n $1 ]]; then
     echo "Unexpected pos. arg: $1"
-    return $PRINT_ES;
+    return $PRINT_ES
   fi
 
-  ! [[ -d $prefix ]] && { echo Prefix $prefix not found; return 1; }
-  ! [[ -d ${folder:=.} ]] && { echo Folder $folder not found; return 1; }
+  ! [[ -d $prefix ]] && {
+    echo Prefix $prefix not found
+    return 1
+  }
+  ! [[ -d ${folder:=.} ]] && {
+    echo Folder $folder not found
+    return 1
+  }
 
   if [[ ${mode:=folder} != folder ]] && [[ $mode != git ]]; then
     echo Invalid mode: $mode
@@ -92,31 +114,38 @@ function difff () {
 
   declare -a files
   if [[ $mode = folder ]]; then
-    shopt -s globstar  # won't work for older Bash shells
-    files=( "${folder%/}"/**/* )
+    shopt -s globstar # won't work for older Bash shells
+    files=("${folder%/}"/**/*)
   else
-    git status &> /dev/null || { echo Not a git project.; return 1; }
-    mapfile -t < <( git diff $staged --name-only "$folder" ) files
+    git status &>/dev/null || {
+      echo Not a git project.
+      return 1
+    }
+    mapfile -t files < <(git diff $staged --name-only "$folder")
   fi
 
   if [[ -z $trim_cnt ]]; then
     local shards
-    IFS='/' read -ra shards <<< "${folder#/}"
+    IFS='/' read -ra shards <<<"${folder#/}"
     trim_cnt=${#shards[@]}
   fi
 
-  echo "$folder (project) .vs. $prefix (counterpart)"
+  echo -ne "$folder ${BGREEN}(project)${NC}"
+  echo -e " .vs. $prefix ${BRED}(counterpart)${NC}"
   echo
 
   local file find_out desc
   declare -a exclude
   if [[ -n $add_new ]]; then
     for counter in "${prefix%/}"/**/*; do
-       matches_path "$counter" "${ignore[@]}" && continue
+      matches_path "$counter" "${ignore[@]}" && continue
 
       file=${folder%/}/${counter/$prefix/}
       if [[ -n ${exclude[*]} ]]; then
-        [[ $file =~ ($(IFS=\|; echo "${exclude[*]}")) ]] && continue
+        [[ $file =~ ($(
+          IFS=\|
+          echo "${exclude[*]}"
+        )) ]] && continue
       fi
 
       ## constructing `file` variable may leave double slash (//),
@@ -125,7 +154,10 @@ function difff () {
 
       if [[ -z $find_out ]]; then
         [[ -d $counter ]] && continue
-        [[ -n $dry_run ]] && { echo "NEW: ${counter}"; continue; }
+        [[ -n $dry_run ]] && {
+          echo "NEW: ${counter}"
+          continue
+        }
 
         desc=
         echo "Not in project: $counter"
@@ -136,23 +168,23 @@ function difff () {
         desc+='Or any other key to continue.\n'
         echo -e $desc
 
-        # read -srk1    # zsh syntaxis
-        read -srn1    # bash syntaxis
+        # read -srk1    # zsh syntax
+        read -srn1 # bash syntax
         case $REPLY in
-          c)
-            mkdir -p "$(dirname "$file")"
-            cp "$counter" "$file" && echo Copied!
-            ;;
-          r)
-            # read -srk1 '?Confirm deletion - [yN] '    # zsh syntaxis
-            read -srn1 -p 'Confirm deletion - [yN] '    # bash syntaxis
-            [[ $REPLY =~ [yY] ]] && rm "$counter"
-            echo
-            ;;
-          e)
-            exclude+=( "$(dirname "$file")" )
-            ;;
-          *)
+        c)
+          mkdir -p "$(dirname "$file")"
+          cp "$counter" "$file" && echo -e "${GREEN}Copied!${NC}"
+          ;;
+        r)
+          # read -srk1 '?Confirm deletion - [yN] '    # zsh syntaxis
+          read -srn1 -p 'Confirm deletion - [yN] ' # bash syntaxis
+          [[ $REPLY =~ [yY] ]] && rm "$counter"
+          echo
+          ;;
+        e)
+          exclude+=("$(dirname "$file")")
+          ;;
+        *) ;;
         esac
       fi
     done
@@ -160,14 +192,21 @@ function difff () {
 
   local counter
   for file in "${files[@]}"; do
-    counter=$(sed -r "s;\/?([^\/]+\/){$trim_cnt}(.*);\2;" <<< "$file")
+    matches_path "$counter" "${ignore[@]}" && continue
+    counter=$(sed -r "s;\/?([^\/]+\/){$trim_cnt}(.*);\2;" <<<"$file")
     counter="${prefix%/}/$counter"
 
     [[ $mode = folder ]] && [[ -d $file || -d $counter ]] && continue
 
     ## Why check `file`? ─ `git diff` reports also deleted.
-    ! [[ -f $file ]] && { echo Not in project: $file; continue; }
-    ! [[ -f $counter ]] && { echo Not in counterpart: $counter; continue; }
+    ! [[ -f $file ]] && {
+      echo Not in project: $counter
+      continue
+    }
+    ! [[ -f $counter ]] && {
+      echo Not in counterpart: $file
+      continue
+    }
 
     if [[ -n $dry_run ]]; then
       echo $file -- $counter
@@ -176,14 +215,18 @@ function difff () {
 
     cmp -s $file $counter && continue
     vimdiff $file $counter
+    sleep 0.28 # small window to abort with <Ctrl-c>
+    ## 250ms - is the avg reaction time
   done
 }
-
 
 difff "$@"
 es=$?
 
 case $es in
-  "$PRINT_ES") echo; help_msg ;;
-  *) exit $es ;;
+"$PRINT_ES")
+  echo
+  help_msg
+  ;;
+*) exit $es ;;
 esac
